### ISSUE TITLE
设计上的严重问题，@input事件

### ISSUE THREAD

**Issue by zhangshichun** [JanssenZhang/vue-drag-select#10]
不知道作者本人是否意识到这个问题，你的数据绑定并不是通过真正意义上的v-model来实现的，而是主要通过prop传递数据，然后调用引用数组的方式在改变传入的数组；

举个例子，我们将v-model语法糖拆开，:value="list" @input="onInput"
methods: {
onInput(v) {
console.log(v)
}
}
你会发现，打印的永远是[]

**Comment by muyiyl** [comment]
> 你会发现，打印的永远是[]

我都拿不到我选的值 大佬解决了吗

**Comment by huangguahuai** [comment]
selectedList
