### ISSUE TITLE
因页面滚动导致框选起点错误

### ISSUE THREAD

**Issue by tianchengcheng-bql** [JanssenZhang/vue-drag-select#24]
如果页面向下滚动了，会导致框选起点错误的增加了页面滚动的高度

**Comment by Gaoshimin** [comment]
@tianchengcheng-bql 遇到同样的问题，页面只要存在滚动条，不管是上下滚动还是左右滚动，都会出现框选位置错误。请问楼主找到解决办法了吗

**Comment by ZhiJieZhang1** [comment]
[https://github.com/ZhiJieZhang1/vue-drag-select/pull/39](https://github.com/ZhiJieZhang1/vue-drag-select/pull/39)
