### ISSUE TITLE
实际使用中每个元素之间的间隙不一定是相同的

### ISSUE THREAD

**Issue by ecojust** [JanssenZhang/vue-drag-select#3]
我看了demo的布局，本地也测试了，单个元素用absolute布局，选中项应该就是根据鼠标绘制区域的坐标结合元素的left、top属性值来确定的，但是并没有提供api来自定义单个元素的位置，item-margin属性通用于所有元素来计算位置，如果需求是像下面这样的呢？
![image](https://user-images.githubusercontent.com/30574854/68444972-7c398500-0213-11ea-97c1-660407a5ef31.png)
建议可以通过dataList单个元素传入margin来计算left、top值(不传就使用默认margin来计算)。

**Comment by ecojust** [comment]
issues2:
![image](https://user-images.githubusercontent.com/30574854/68445559-37aee900-0215-11ea-83e0-edd1f4109998.png)
我现在是通过修改透明度来显示/隐藏元素，这样已选中元素看起来是25-7=18个，但是实际上此时selectedList里还是25个的，所以是否能够添加一个鼠标离开的事件回调(其实也就是选择结束的回调)来过滤这些本不该被放入selectedList里的选项，或者直接添加一个filter数组，每次选择结束之后组件自行过滤

**Comment by ZhiJieZhang1** [comment]
你好，
issue1，我只明白了你需要个别元素需要特定位置，但是不是很明白这样的需求是出于什么。
issue2，实际的demo能否添加到这里[codesand](https://codesandbox.io/s/vue)

**Comment by ecojust** [comment]
@JanssenZhang 我急着用，最后还是自己写了一个这样的组件

<img width="1210" alt="WechatIMG46" src="https://user-images.githubusercontent.com/30574854/69160840-2c1cc580-0b25-11ea-9fb9-dc9070eba477.png">

![image](https://user-images.githubusercontent.com/30574854/69161132-9e8da580-0b25-11ea-8fa4-91ea6b40df34.png)

支持根据单个数据的top，left属性值来自定义位置，框选，逐个选择/取消元素，单击回调，hover回调

**Comment by ZhiJieZhang1** [comment]
@ecojust 可以的，改一下布局函数就好了，你很棒！当然，如果你觉得帮得到你的话，可以star一下，😁
